### ISSUE TITLE
Documentation website not accessible :(

### ISSUE THREAD

**Issue by andreybleme** [bamos/parsec-benchmark#7]
Hi @bamos, I noticed the website http://parsec.cs.princeton.edu/ is not accessible.

Was it migrated to another domain? 

I'd love to have access to the docs to use server/client mode network benchmarks.

Thanks for making this open!

**Comment by danielcatu** [comment]
The same here but in my case it has not been possible to get the dataset to be able to run the benckmark.
Any information would be helpful.
Thanks.

**Comment by LepingLi0810** [comment]
I guess Princeton just closed the site. I am also looking for the dataset :(

**Comment by LukeJYK** [comment]
https://github.com/cirosantilli/parsec-benchmark/releases/tag/3.0 may be helpful.
