### ISSUE TITLE
other inputs

### ISSUE THREAD

**Issue by Yitrus** [bamos/parsec-benchmark#8]
Hi，
Where I can find other inputs except 'test' and 'simdev' ？Or how can I build other input？None of these seem to have been mentioned in readme. I once downloaded them directly from the link on the PARSEC official website. However, the website is currently inaccessible.

**Comment by LukeJYK** [comment]
same issue. https://github.com/cirosantilli/parsec-benchmark/releases/tag/3.0 may be helpful.
